### ISSUE TITLE
Please add my blog [redacted identity]

### ISSUE THREAD

**Issue by mrmannet** [uxai/non-profit-bloggers#11]
1. **Category**  Personal / Rambling
2. **Title of the blog**  [redacted identity]
3. **URL**  https://sus.fr/en/blog/
4. **(Optional) Emoji that represents your blog, this will be displayed before the name of your blog.**  🫠
5. **Let me know the Author name to feature and if you would like to link your github.**  Author name as Kévin and no link to github please

_Side note : the server it's running on has been a tad unstable in the last couple days for some reason, so if you get a 503 error or its down, retry again in a few hours when I reset it_

**Comment by uxai** [comment]
Thanks, this has been added.
