### ISSUE TITLE
Can I Join?

### ISSUE THREAD

**Issue by jackeyjack1** [uxai/non-profit-bloggers#12]
Category:
Education / Psychology / Personal / Life / the Internet

Title of the blog:
foreverliketh.is

URL:
https://foreverliketh.is/

RSS Feed URL:
https://foreverliketh.is/blog/index.xml

(Optional) Emoji that represents your blog, this will be displayed before the name of your blog:
🌱

Let me know the Author name to feature:
foreverliketh.is

and if you would like to link your github:
No

**Comment by uxai** [comment]
Hi there, it looks like your blog is more of a tumbler / link sharing type feed? I couldn't find any articles.

**Comment by jackeyjack1** [comment]
Hello, thank you for the communication. Please, could you double-check here:

https://foreverliketh.is/blog

The RSS feed (.xml) is for those blog articles.

**Comment by jackeyjack1** [comment]
Thank you!!
