### ISSUE TITLE
new blog: d-s

### ISSUE THREAD

**Issue by michalsapka** [uxai/non-profit-bloggers#13]
Hey, not sure if I should add an issue or a PR but here we go

Category: Personal / Tech / Media
Title of the blog: d-s
URL: https://d-s.sh
RSS Feed URL: https://d-s.sh/index.xml
(Optional) Emoji: none
author name: d-s

:-)

**Comment by uxai** [comment]
Hey there, sorry for the delay. I've added your blog :)
