### ISSUE TITLE
Blog submission - lukealexdavis.co.uk

### ISSUE THREAD

**Issue by starchildluke** [uxai/non-profit-bloggers#15]
Category - Personal
Title of the blog - Luke Alex Davis
URL - [https://lukealexdavis.co.uk/](https://lukealexdavis.co.uk/)
RSS Feed URL - [https://lukealexdavis.co.uk/blog.xml](https://lukealexdavis.co.uk/blog.xml)
Emoji that represents your blog - 🤌🏽
Author name - Luke Alex Davis

**Comment by uxai** [comment]
I have added your blog, please don't forget to checkout our new discord as well :)
