### ISSUE TITLE
Blog to add

### ISSUE THREAD

**Issue by colin-walker** [uxai/non-profit-bloggers#2]
What a great idea. I know there are a number of places collecting personal blogs at the moment but you can't have too many.

Would it also be an idea to include people's profiles on GitHub if they have submitted it that way so you can see if they're up to anything interesting/relevant?

Category: Personal/Random
Title of the blog: Colin Walker
URL: https://colinwalker.blog
Emoji: 🤔 or 👋

I've posted about the repo [here](https://colinwalker.blog/blog/?date=2023-02-14#p1).

**Comment by uxai** [comment]
Thanks for your contribution! Yes its a great idea - I will modify to let people opt into having their github shared too.
________________________________
From: Colin Walker ***@***.***>
Sent: Tuesday, February 14, 2023 8:08 PM
To: uxai/non-profit-bloggers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [uxai/non-profit-bloggers] Blog to add (Issue #2)


What a great idea. I know there are a number of places collecting personal blogs at the moment but you can't have too many.

Would it also be an idea to include people's profiles on GitHub if they have submitted it that way so you can see if they're up to anything interesting/relevant?

Category: Personal/Random
Title of the blog: Colin Walker
URL: https://colinwalker.blog
Emoji: 🤔 or 👋

I've posted about the repo here<https://colinwalker.blog/blog/?date=2023-02-14#p1>.

**Comment by uxai** [comment]
Added!
