### ISSUE TITLE
Request to Add Blog

### ISSUE THREAD

**Issue by am1t** [uxai/non-profit-bloggers#3]
Another interesting idea. Every mechanism to discover new blogs from people who write for themselves is welcome. Here's mine.

Category - Personal / Life / Writing
Title of the blog - Excursions
URL - https://amitgawande.com
Emoji - 🤓

**Comment by uxai** [comment]
Thanks! Would you also like to have your github profile shared too?
________________________________
From: Amit Gawande ***@***.***>
Sent: Tuesday, February 14, 2023 8:55 PM
To: uxai/non-profit-bloggers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [uxai/non-profit-bloggers] Request to Add Blog (Issue #3)


Another interesting idea. Every mechanism to discover new blogs from people who write for themselves is welcome. Here's mine.

Category - Personal / Life / Writing
Title of the blog - Excursions
URL - https://amitgawande.com
Emoji - 🤓

**Comment by am1t** [comment]
Sure. I am ok with that. Thank you! 👍🏽

**Comment by uxai** [comment]
Great! I've added :)
