### ISSUE TITLE
This is the internet weblog of Bix Frankonis.

### ISSUE THREAD

**Issue by bixfrankonis** [uxai/non-profit-bloggers#8]
1. Category  
    Personal / Actually-Autistic / Random
3. Title of the blog  
    This is the internet weblog of Bix Frankonis.
5. URL  
    https://bix.blog
7. (Optional) Emoji that represents your blog, this will be displayed before the name of your blog.  
    👋
8. Let me know the Author name to feature and if you would like to link your github.  
    Bix Frankonis, no link to GitHub

**Comment by uxai** [comment]
Thank you, it will be added in a few minutes :)
