### ISSUE TITLE
Oblivion With Bells: An enquiry into life and death, and what we believe.

### ISSUE THREAD

**Issue by dave-underwood** [uxai/non-profit-bloggers#9]
Category: Psychology/Existentialism
Title of the blog: Oblivion With Bells
URL: [https://oblivionwithbells.com/](https://oblivionwithbells.com/)
Emoji that represents your blog: 🖤
Author name to feature: [Dave Underwood](https://github.com/dave-underwood)

**Comment by uxai** [comment]
Thanks, this has been added :)
